In [1]:
# Declare Dependencies
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
csv_df = pd.read_csv('DesertInn.csv')
csv_df_edited = csv_df
csv_df_edited.head(10)

Reservation_No DateMade_Short Arrive_Date_Short  Nights  TotalRate  \
0               1     28/06/2016        21/07/2016       3     258.02   
1              13     28/06/2016        14/07/2016       3     223.50   
2              15     28/06/2016        14/07/2016       1     420.00   
3              16     28/06/2016        16/07/2016       1      66.80   
4              17     28/06/2016        17/07/2016       4     540.00   
5              18     28/06/2016        21/07/2016       3     258.00   
6              19     28/06/2016        21/07/2016       3     283.82   
7              20     28/06/2016        22/07/2016       2     206.00   
8            1340     17/10/2016        30/10/2016       2     158.00   
9              24     28/06/2016        25/07/2016       2     247.00   

         Room Type    Room        City State Zip Code            Rate_Type  
0          Double      210    Bellevue    WA    98004  Best Available Rate  
1          Double      108      Aurora    IL    60506  Best Available Rate  
2          Double      208         NaN   NaN      NaN  Best Available Rate  
3             King     107    Bellevue    WA    98004  Best Available Rate  
4  Rubideaux Condo  Rub #4     Seattle    WA    98117  Best Available Rate  
5          Double      106    Bellevue    WA    98004  Best Available Rate  
6     Premier King     105    Bellevue    WA    98004  Best Available Rate  
7             King     203  Snellville    FL    30039  Best Available Rate  
8  Sweetheart King     102  Palm Coast    FL    32137  Best Available Rate  
9          Double      106     Reddick    MA    32686  Best Available Rate

In [3]:
csv_df_edited.dtypes

Reservation_No         int64
DateMade_Short        object
Arrive_Date_Short     object
Nights                 int64
TotalRate            float64
Room Type             object
Room                  object
City                  object
State                 object
Zip Code              object
Rate_Type             object
dtype: object

In [4]:
csv_df_edited[['booking_day','booking_month','booking_year']] = csv_df_edited['DateMade_Short'].str.split('/', expand=True).astype(int)
csv_df_edited[['reservation_day','reservation_month','reservation_year']] = csv_df_edited['Arrive_Date_Short'].str.split('/', expand=True).astype(int)
print (csv_df_edited.dtypes)
csv_df_edited.head()
csv_df_edited.count()

Reservation_No         int64
DateMade_Short        object
Arrive_Date_Short     object
Nights                 int64
TotalRate            float64
Room Type             object
Room                  object
City                  object
State                 object
Zip Code              object
Rate_Type             object
booking_day            int32
booking_month          int32
booking_year           int32
reservation_day        int32
reservation_month      int32
reservation_year       int32
dtype: object


Reservation_No       7880
DateMade_Short       7880
Arrive_Date_Short    7880
Nights               7880
TotalRate            7880
Room Type            7880
Room                 7880
City                 3443
State                1109
Zip Code             3121
Rate_Type            7880
booking_day          7880
booking_month        7880
booking_year         7880
reservation_day      7880
reservation_month    7880
reservation_year     7880
dtype: int64

In [5]:
print (csv_df_edited.booking_day.unique())
print (csv_df_edited.reservation_day.unique())
print (csv_df_edited.booking_year.unique())
print (csv_df_edited.reservation_year.unique())
print (csv_df_edited.booking_month.unique())
print (csv_df_edited.reservation_month.unique())

[28 17  6 25 19 29 30  1  2 18  7  3 31  5  4  9 10 13 11 12 24 14 15 16
 20 27 21 22 23 26  8]
[21 14 16 17 22 30 25 26  3 31  1 19 18  4  6 15 12 13  8 23 24 28 20  7
 29  2 10 11 27  9  5]
[2016 2018 2017 2019]
[2016 2018 2017 2019]
[ 6 10  2  7 11  4  1  9  8  3  5 12]
[ 7 10  3  8 11  9  5  4  2  1 12  6]


In [6]:
csv_df_edited['booking_date']= pd.to_datetime(csv_df_edited.booking_year*10000+csv_df_edited.booking_month*100+csv_df_edited.booking_day,format='%Y%m%d')
csv_df_edited['reservation_date']= pd.to_datetime(csv_df_edited.reservation_year*10000+csv_df_edited.reservation_month*100+csv_df_edited.reservation_day,format='%Y%m%d')
print(csv_df_edited.dtypes)
csv_df_edited.head()

Reservation_No                int64
DateMade_Short               object
Arrive_Date_Short            object
Nights                        int64
TotalRate                   float64
Room Type                    object
Room                         object
City                         object
State                        object
Zip Code                     object
Rate_Type                    object
booking_day                   int32
booking_month                 int32
booking_year                  int32
reservation_day               int32
reservation_month             int32
reservation_year              int32
booking_date         datetime64[ns]
reservation_date     datetime64[ns]
dtype: object


Reservation_No DateMade_Short Arrive_Date_Short  Nights  TotalRate  \
0               1     28/06/2016        21/07/2016       3     258.02   
1              13     28/06/2016        14/07/2016       3     223.50   
2              15     28/06/2016        14/07/2016       1     420.00   
3              16     28/06/2016        16/07/2016       1      66.80   
4              17     28/06/2016        17/07/2016       4     540.00   

         Room Type    Room      City State Zip Code            Rate_Type  \
0          Double      210  Bellevue    WA    98004  Best Available Rate   
1          Double      108    Aurora    IL    60506  Best Available Rate   
2          Double      208       NaN   NaN      NaN  Best Available Rate   
3             King     107  Bellevue    WA    98004  Best Available Rate   
4  Rubideaux Condo  Rub #4   Seattle    WA    98117  Best Available Rate   

   booking_day  booking_month  booking_year  reservation_day  \
0           28              6          2016               21   
1           28              6          2016               14   
2           28              6          2016               14   
3           28              6          2016               16   
4           28              6          2016               17   

   reservation_month  reservation_year booking_date reservation_date  
0                  7              2016   2016-06-28       2016-07-21  
1                  7              2016   2016-06-28       2016-07-14  
2                  7              2016   2016-06-28       2016-07-14  
3                  7              2016   2016-06-28       2016-07-16  
4                  7              2016   2016-06-28       2016-07-17

In [7]:
csv_df_edited.drop(['DateMade_Short', 'Arrive_Date_Short', 'booking_year','booking_day', 'booking_month','reservation_year','reservation_month','reservation_day'], axis=1, inplace=True)
csv_df_edited.head()

Reservation_No  Nights  TotalRate        Room Type    Room      City State  \
0               1       3     258.02          Double      210  Bellevue    WA   
1              13       3     223.50          Double      108    Aurora    IL   
2              15       1     420.00          Double      208       NaN   NaN   
3              16       1      66.80             King     107  Bellevue    WA   
4              17       4     540.00  Rubideaux Condo  Rub #4   Seattle    WA   

  Zip Code            Rate_Type booking_date reservation_date  
0    98004  Best Available Rate   2016-06-28       2016-07-21  
1    60506  Best Available Rate   2016-06-28       2016-07-14  
2      NaN  Best Available Rate   2016-06-28       2016-07-14  
3    98004  Best Available Rate   2016-06-28       2016-07-16  
4    98117  Best Available Rate   2016-06-28       2016-07-17

In [8]:
#create output dataframe
results = []

for index, row in csv_df_edited.iterrows():
    for x in range(row['Nights']):
        reservation_no = row['Reservation_No']
        room_no = row['Room']
        total_nights = row['Nights']
        total_rate = row['TotalRate']
        avg_daily_rate  = total_rate/total_nights
        room_type = row['Room Type']
        rate_type = row['Rate_Type']
        booking_date = row['booking_date']
        reservation_date = row['reservation_date']+datetime.timedelta(days=x)
        reservation_weekday = reservation_date.strftime("%A")
        reservation_date_short = reservation_date.strftime("%d, %B")
        tester = {'reservation_no':reservation_no, 'room_no': room_no, 'total_nights': total_nights,'total_rate': total_rate, 'avg_daily_rate': avg_daily_rate, 'room_type': room_type, 'rate_type':rate_type, 'booking_date':booking_date, 'reservation_date':reservation_date, 'reservation_weekday':reservation_weekday,'reservation_date_short':reservation_date_short}
        results.append(tester)
        
results_df = pd.DataFrame(results)
results_df.head()

reservation_no room_no  total_nights  total_rate  avg_daily_rate room_type  \
0               1     210             3      258.02       86.006667   Double    
1               1     210             3      258.02       86.006667   Double    
2               1     210             3      258.02       86.006667   Double    
3              13     108             3      223.50       74.500000   Double    
4              13     108             3      223.50       74.500000   Double    

             rate_type booking_date reservation_date reservation_weekday  \
0  Best Available Rate   2016-06-28       2016-07-21            Thursday   
1  Best Available Rate   2016-06-28       2016-07-22              Friday   
2  Best Available Rate   2016-06-28       2016-07-23            Saturday   
3  Best Available Rate   2016-06-28       2016-07-14            Thursday   
4  Best Available Rate   2016-06-28       2016-07-15              Friday   

  reservation_date_short  
0               21, July  
1               22, July  
2               23, July  
3               14, July  
4               15, July

In [9]:
results_df.to_csv('results_exported.csv')

In [10]:
results1_df = results_df.drop(columns=['reservation_no', 'room_no', 'total_rate', 'rate_type', 'booking_date', 'reservation_date', 'reservation_weekday', 'reservation_date_short'])
results1_df

total_nights  avg_daily_rate room_type
0                 3       86.006667   Double 
1                 3       86.006667   Double 
2                 3       86.006667   Double 
3                 3       74.500000   Double 
4                 3       74.500000   Double 
...             ...             ...       ...
13959            29       37.758621      King
13960            29       37.758621      King
13961            29       37.758621      King
13962            29       37.758621      King
13963            29       37.758621      King

[13964 rows x 3 columns]

In [11]:
# Drop a row by condition
results2_df = results1_df[results1_df.room_type != 'King']
results3_df = results2_df[results2_df.room_type != 'Upscale Jacuzzi King']
results4_df = results3_df[results3_df.room_type != 'Rubideaux Condo']
results5_df = results4_df[results4_df.room_type != 'Sweetheart King']
results6_df = results5_df[results5_df.room_type != 'Upscale King']
results7_df = results6_df[results6_df.room_type != 'Premier King']
df = results7_df.drop(columns=['room_type'])
df.head()

total_nights  avg_daily_rate
0             3       86.006667
1             3       86.006667
2             3       86.006667
3             3       74.500000
4             3       74.500000

In [12]:
#Calculate meanvalues of duplicate entries of total_nights
df1 = df.groupby('total_nights').mean().reset_index()
df1.head()

total_nights  avg_daily_rate
0             1       84.892816
1             2       96.111111
2             3       94.719765
3             4       97.785599
4             5       87.354444

# Quantifying Linear Regression

In [13]:
# Import dependencies
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression

# Generate some data
X1, y1 = make_regression(n_samples=20, n_features=1, random_state=0, noise=4, bias=100.0)

# Create a linear model
model = LinearRegression()

# Fit (Train) our model to the data
model.fit(X1, y1)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# Quantifying our Model
*Mean Squared Error (MSE)
*R2 Socre

In [14]:
from sklearn.metrics import mean_squared_error, r2_score

# Use our model to predict a value
predicted = model.predict(X1)

# Score the prediction with mse and r2
mse = mean_squared_error(y1, predicted)
r2 = r2_score(y1, predicted)

print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2 ): {r2}")

Mean Squared Error (MSE): 11.933040779746149
R-squared (R2 ): 0.903603363418708


In [15]:
# Overall Score for the model
model.score(X1, y1)

0.903603363418708

# Validation
We also want to understand how well our model performs on new data.
One approach for this is to split your data into a training and testing dataset.
You fit (train) the model using training data, and score and validate your model using the testing data.
This train/test splitting is so common that Sklearn provides a mechanism for doing this.

# Testing and Training Data
In order to quantify our model against new input values, we often split the data into training and testing data. The model is then fit to the training data and scored by the test data. Sklean pre-processing provides a library for automatically splitting up the data into training and testing

In [25]:
from sklearn.model_selection import train_test_split

X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, random_state=42)

In [26]:
model.fit(X1_train, y1_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
model.score(X1_test, y1_test)

-0.1358304027061017

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
model = LinearRegression()

In [20]:
X1 = df1.drop('avg_daily_rate', axis='columns')
X1

total_nights
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10
10            11
11            14
12            21
13            22
14            25
15            26
16            29
17            30
18            31

In [21]:
y1 = df1.avg_daily_rate
y1

0      84.892816
1      96.111111
2      94.719765
3      97.785599
4      87.354444
5      79.336296
6      89.275649
7      99.468750
8      86.888889
9      85.217500
10     83.509091
11     43.170000
12     66.428571
13    106.909091
14     47.800000
15     50.683462
16     65.034483
17     40.123810
18     40.935484
Name: avg_daily_rate, dtype: float64

In [22]:
model.fit(X1_train, y1_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
model.predict([[5]])


array([95.6003737])

In [28]:
from sklearn.metrics import mean_squared_error, r2_score

# Use our model to predict a value
predicted = model.predict(X1)

# Score the prediction with mse and r2
mse = mean_squared_error(y1, predicted)
r2 = r2_score(y1, predicted)

print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2 ): {r2}")

Mean Squared Error (MSE): 228.93915338006235
R-squared (R2 ): 0.49615271453677245


In [30]:
# Overall Score for the model
model.score(X1, y1)

0.49615271453677245